update(*): divide code by modules
htmlacademy-javascript/1817617-keksobooking-23 pull request #4
Opened 2021-06-11 08:07 UTC by ostoliar

2021-06-12 21:34 UTC, lutogin requested changes

2021-06-12 21:34 UTC, lutogin commented on js/random-number.js
> +  function showErrorMessage() {
Зачем функция в функции и там же вызов?

2021-06-12 21:34 UTC, lutogin commented on js/random-number.js
> +      throw new Error('«до» меньшее, чем значение «от»');
throw new Error это было взято с лекции?
Я просто не вижу где ты обрабатываешь исключение

2021-06-12 21:34 UTC, lutogin commented on js/random-number.js
> +      throw new Error('«до» меньшее, чем значение «от»');
как я понял этот метод должен вернуть только true/false а не выброс ошибки

2021-06-12 21:34 UTC, lutogin commented on js/random-number.js
> +    return;
а вот тут бы нужно обработать и вывести сообщение, а не просто return

2021-06-13 20:47 UTC, ostoliar commented on js/random-number.js
> +  function showErrorMessage() {
Тут поправил можно смотреть.

2021-06-13 20:48 UTC, ostoliar commented on js/random-number.js
> +      throw new Error('«до» меньшее, чем значение «от»');
Была задача написать функцию, которая выведет рандомное число из введенного диапазона и придумать как будет вести себя функция если ввести значение от больше чем значение до в этом диапазоне. Вот я и придумал функцию validate. В try, catch ошибка обрабатывается и вроде все нормально работает. Я не совсем понимаю, что мне тут править и вообще нужен ли тут этот функционал, так как функция была придумана в соответствии с заданием и для выполнения выбранного проэкта это может и не нужно совсем. Можешь предложить свои соображения по поводу рефакторинга? Я так понимаю, что все что мы сейчас делаем должно пригодиться для выполнения выбранного проэкта? Возможно в проэкте я просто буду запрещать отправку формы, а не выводить сообщение о неправильности введенных данных?

2021-06-17 14:41 UTC, aluto-ss requested changes

2021-06-17 14:41 UTC, aluto-ss commented on js/random-number.js
> +function getRandomNumber(from, to) {
Уже лучше, давай еще до полируем до такого вида:
getRandomNumber будет возвращать обьект формата 
```
{
  error: boolean; // true - ошибка валидации false - все ок
  msg: string; // сообщение в случае ошибки. это полу только в случае если свалилась валидация
  data: bumber; // наше рандом число. это полу только в случае что все ок
}
```
А далее уже чекаем if (response.error) {
  showErrorMessage(response.msg);
}

2021-06-17 14:41 UTC, aluto-ss commented on js/random-number.js
> +function getRandomCoordinates(from, to, quantityAfterDecimal) {
тут аналогично

2021-06-18 16:07 UTC, merged